name: Deploy Quiz API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start app
        run: npm run start
        env:
          NODE_ENV: production
          API_TOKEN: ${{ secrets.API_TOKEN }}
          PORT: 8080
